### ISSUE TITLE
Ahoy : Deploying Rails App on heroku Get undefined method `years' for 2:Fixnum 

### ISSUE THREAD

**Issue by Shahidrox** [ankane/ahoy#107]
I am deploying my rails app on heroku and i was facing an issue.
**I get this error**

```ruby
rake aborted!
remote:        NoMethodError: undefined method `years' for 2:Fixnum
remote:        /tmp/build_78e0bbab0eb281751dec115ddacb4473/vendor/bundle/ruby/2.0.0/gems/ahoy_matey-1.1.1/lib/ahoy.rb:47:in `<module:Ahoy>'
remote:        /tmp/build_78e0bbab0eb281751dec115ddacb4473/vendor/bundle/ruby/2.0.0/gems/ahoy_matey-1.1.1/lib/ahoy.rb:40:in `<top (required)>'
remote:        /tmp/build_78e0bbab0eb281751dec115ddacb4473/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:251:in `require'
remote:        /tmp/build_78e0bbab0eb281751dec115ddacb4473/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:251:in `block in require'
remote:        /tmp/build_78e0bbab0eb281751dec115ddacb4473/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:236:in `load_dependency'
remote:        /tmp/build_78e0bbab0eb281751dec115ddacb4473/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:251:in `require'
remote:        /tmp/build_78e0bbab0eb281751dec115ddacb4473/vendor/bundle/ruby/2.0.0/gems/ahoy_matey-1.1.1/lib/ahoy_matey.rb:1:in `<top (required)>'
remote:        /tmp/build_78e0bbab0eb281751dec115ddacb4473/vendor/bundle/ruby/2.0.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:76:in `require'
remote:        /tmp/build_78e0bbab0eb281751dec115ddacb4473/vendor/bundle/ruby/2.0.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
remote:        /tmp/build_78e0bbab0eb281751dec115ddacb4473/vendor/bundle/ruby/2.0.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:72:in `each'
remote:        /tmp/build_78e0bbab0eb281751dec115ddacb4473/vendor/bundle/ruby/2.0.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:72:in `block in require'
remote:        /tmp/build_78e0bbab0eb281751dec115ddacb4473/vendor/bundle/ruby/2.0.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:61:in `each'
remote:        /tmp/build_78e0bbab0eb281751dec115ddacb4473/vendor/bundle/ruby/2.0.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:61:in `require'
remote:        /tmp/build_78e0bbab0eb281751dec115ddacb4473/vendor/bundle/ruby/2.0.0/gems/bundler-1.9.7/lib/bundler.rb:134:in `require'
remote:        /tmp/build_78e0bbab0eb281751dec115ddacb4473/config/application.rb:7:in `<top (required)>'
remote:        /tmp/build_78e0bbab0eb281751dec115ddacb4473/Rakefile:5:in `require'
remote:        /tmp/build_78e0bbab0eb281751dec115ddacb4473/Rakefile:5:in `<top (required)>'
remote:        /tmp/build_78e0bbab0eb281751dec115ddacb4473/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load'
remote:        /tmp/build_78e0bbab0eb281751dec115ddacb4473/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load_rakefile'
remote:        /tmp/build_78e0bbab0eb281751dec115ddacb4473/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:689:in `raw_load_rakefile'
remote:        /tmp/build_78e0bbab0eb281751dec115ddacb4473/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:94:in `block in load_rakefile'
remote:        /tmp/build_78e0bbab0eb281751dec115ddacb4473/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
remote:        /tmp/build_78e0bbab0eb281751dec115ddacb4473/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:93:in `load_rakefile'
remote:        /tmp/build_78e0bbab0eb281751dec115ddacb4473/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:77:in `block in run'
remote:        /tmp/build_78e0bbab0eb281751dec115ddacb4473/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
remote:        /tmp/build_78e0bbab0eb281751dec115ddacb4473/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
remote:        /tmp/build_78e0bbab0eb281751dec115ddacb4473/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
remote:        vendor/bundle/bin/rake:16:in `load'
remote:        vendor/bundle/bin/rake:16:in `<main>'

```

**Comment by ankane** [comment]
@Shahidrox It seems like ActiveSupport extensions aren't being loaded before Ahoy. Try the master branch to see if that fixes it.
