### ISSUE TITLE
Visitor Cookie Not being set

### ISSUE THREAD

**Issue by erhimanshugoyal** [ankane/ahoy#192]
NoMethodError (undefined method `set_visitor_cookie' for #<Ahoy::Tracker:0x00000006dca978>):
  ahoy_matey (1.4.2) lib/ahoy/controller.rb:28:in`set_ahoy_cookies'
  activesupport (4.2.6) lib/active_support/callbacks.rb:432:in `block in make_lambda'
  activesupport (4.2.6) lib/active_support/callbacks.rb:164:in`call'

Can someone please tell me what have i done wrong?

**Comment by ankane** [comment]
Haven't seen that error before. The method exists here: https://github.com/ankane/ahoy/blob/v1.4.2/lib/ahoy/tracker.rb#L78

Are you overriding the `Ahoy::Tracker` anywhere in your project?

**Comment by ankane** [comment]
Closing due to lack of response.

**Comment by patakijv** [comment]
@ankane I am in the middle of the process of migrating a Rails 3 app that has been using the Ahoy gem just fine to Rails 4 and I am getting the message described by OP. As you say the method `set_visitor_cookie` does exist in the tracker.  What would cause this to be called before the tracker is loaded? I've made the changes in the wiki for migrating to Ahoy 2 already.

Here is the full error stack

```
NoMethodError (undefined method `set_visitor_cookie' for #<ActionDispatch::Routing::RoutesProxy:0x00000006653208>):
  actionpack (4.2.10) lib/action_dispatch/routing/routes_proxy.rb:37:in `method_missing'
  ahoy_matey (2.1.0) lib/ahoy/controller.rb:28:in `set_ahoy_cookies'
  activesupport (4.2.10) lib/active_support/callbacks.rb:432:in `block in make_lambda'
  activesupport (4.2.10) lib/active_support/callbacks.rb:145:in `block in halting_and_conditional'
  activesupport (4.2.10) lib/active_support/callbacks.rb:504:in `block in call'
  activesupport (4.2.10) lib/active_support/callbacks.rb:504:in `each'
  activesupport (4.2.10) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.10) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.10) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.10) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.10) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.10) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.10) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.10) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.10) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.10) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.10) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.10) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.10) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.10) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.10) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.10) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.10) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.10) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.10) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.10) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.10) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.10) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.10) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.10) lib/action_dispatch/routing/route_set.rb:817:in `call'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  exception_notification (4.2.2) lib/exception_notification/rack.rb:41:in `call'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  newrelic_rpm (5.3.0.346) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  newrelic_rpm (5.3.0.346) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack-attack (4.3.1) lib/rack/attack.rb:106:in `call'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
  warden (1.2.7) lib/warden/manager.rb:35:in `catch'
  warden (1.2.7) lib/warden/manager.rb:35:in `call'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (1.6.10) lib/rack/etag.rb:24:in `call'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (1.6.10) lib/rack/conditionalget.rb:25:in `call'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (1.6.10) lib/rack/head.rb:13:in `call'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/flash.rb:260:in `call'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (1.6.10) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.10) lib/rack/session/abstract/id.rb:220:in `call'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  activerecord (4.2.10) lib/active_record/query_cache.rb:36:in `call'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  activerecord (4.2.10) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.10) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.10) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.10) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.10) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  railties (4.2.10) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.10) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.10) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.10) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.10) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.10) lib/rails/rack/logger.rb:20:in `call'
  ahoy_matey (2.1.0) lib/ahoy/engine.rb:20:in `call_with_quiet_ahoy'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (1.6.10) lib/rack/methodoverride.rb:22:in `call'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (1.6.10) lib/rack/runtime.rb:18:in `call'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  activesupport (4.2.10) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (1.6.10) lib/rack/lock.rb:17:in `call'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/static.rb:120:in `call'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (1.6.10) lib/rack/sendfile.rb:113:in `call'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  railties (4.2.10) lib/rails/engine.rb:518:in `call'
  railties (4.2.10) lib/rails/application.rb:165:in `call'
  railties (4.2.10) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.10) lib/rails/railtie.rb:194:in `method_missing'
  newrelic_rpm (5.3.0.346) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by dongtong** [comment]
@ankane I have same issue, I can not track from javascript
