### ISSUE TITLE
How do I add associations to the Visit object

### ISSUE THREAD

**Issue by palidanx** [ankane/ahoy#275]
In the visit object, I want to add an association, let's call it region

```
class Visit < ActiveRecord::Base
  has_many :ahoy_events, class_name: "Ahoy::Event"
  belongs_to :user
  belongs_to :region
```

However when I run my site I get
```
ActiveRecord::AssociationTypeMismatch (Region(#69866472715700) expected, got String(#15001460)):
  activerecord (3.2.22) lib/active_record/associations/association.rb:210:in `raise_on_type_mismatch'
  activerecord (3.2.22) lib/active_record/associations/belongs_to_association.rb:6:in `replace'
  activerecord (3.2.22) lib/active_record/associations/singular_association.rb:17:in `writer'
  activerecord (3.2.22) lib/active_record/associations/builder/association.rb:51:in `block in define_writers'
  ahoy_matey (1.6.0) lib/ahoy/stores/base_store.rb:70:in `block in set_visit_properties'
  ahoy_matey (1.6.0) lib/ahoy/stores/base_store.rb:69:in `each'
  ahoy_matey (1.6.0) lib/ahoy/stores/base_store.rb:69:in `set_visit_properties'
  ahoy_matey (1.6.0) lib/ahoy/stores/active_record_token_store.rb:14:in `track_visit'
  ahoy_matey (1.6.0) lib/ahoy/tracker.rb:43:in `track_visit'
  ahoy_matey (1.6.0) app/controllers/ahoy/visits_controller.rb:4:in `create'
```

Specifically it seems to be complaining about
https://github.com/ankane/ahoy/blob/master/lib/ahoy/tracker.rb
```
def track_visit(options, &block)
        @visit =
          visit_model.new do |v|
            v.visit_token = ahoy.visit_token
            v.visitor_token = ahoy.visitor_token
            v.user = user if v.respond_to?(:user=)
            v.started_at = options[:started_at] if v.respond_to?(:started_at)
            v.created_at = options[:started_at] if v.respond_to?(:created_at)
          end

        set_visit_properties(visit)
```

I'm a little confused as to why this seems to be happening.  Any guidance on how to add an association?

**Comment by ankane** [comment]
Hey @palidanx, `region` is used for geocoding, so you'll need to use a different association name.

https://github.com/ankane/ahoy/blob/master/lib/ahoy/visit_properties.rb#L7
