### ISSUE TITLE
Ahoy is not recording visits on Heroku out-of-the-box. Can't fix.

### ISSUE THREAD

**Issue by andrisole92** [ankane/ahoy#451]
Hi,

First of all, I like this gem, but it does not work on Heroku for some reason...

Relevant lines from Gemfile

```
ruby '2.4.1'
gem "ahoy_matey", github: "ankane/ahoy"
gem 'device_detector'
gem 'rails', '~> 5.2.2'
```

Lines from ahoy.rb

```
class Ahoy::Store < Ahoy::DatabaseStore
end

# set to true for JavaScript tracking
Ahoy.api = false
Ahoy.quiet = false
```

Help is highly appreciated!

Thanks!

**Comment by andrisole92** [comment]
trace:

```
2020-07-11T18:35:17.072762+00:00 app[web.1]: F, [2020-07-11T18:35:17.072686 #4] FATAL -- : [e15e2d43-88ce-4f5b-ba53-a7fd1984a65e] vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
2020-07-11T18:35:17.072763+00:00 app[web.1]: [e15e2d43-88ce-4f5b-ba53-a7fd1984a65e] vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
2020-07-11T18:35:17.072765+00:00 app[web.1]: [e15e2d43-88ce-4f5b-ba53-a7fd1984a65e] vendor/bundle/ruby/2.4.0/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:38:in `call_app'
2020-07-11T18:35:17.072766+00:00 app[web.1]: [e15e2d43-88ce-4f5b-ba53-a7fd1984a65e] vendor/bundle/ruby/2.4.0/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:26:in `block in call'
2020-07-11T18:35:17.072766+00:00 app[web.1]: [e15e2d43-88ce-4f5b-ba53-a7fd1984a65e] vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
2020-07-11T18:35:17.072766+00:00 app[web.1]: [e15e2d43-88ce-4f5b-ba53-a7fd1984a65e] vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:28:in `tagged'
2020-07-11T18:35:17.072767+00:00 app[web.1]: [e15e2d43-88ce-4f5b-ba53-a7fd1984a65e] vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:71:in `tagged'
2020-07-11T18:35:17.072767+00:00 app[web.1]: [e15e2d43-88ce-4f5b-ba53-a7fd1984a65e] vendor/bundle/ruby/2.4.0/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:26:in `call'
2020-07-11T18:35:17.072768+00:00 app[web.1]: [e15e2d43-88ce-4f5b-ba53-a7fd1984a65e] vendor/bundle/ruby/2.4.0/bundler/gems/ahoy-9a270688b867/lib/ahoy/engine.rb:22:in `call_with_quiet_ahoy'
2020-07-11T18:35:17.072768+00:00 app[web.1]: [e15e2d43-88ce-4f5b-ba53-a7fd1984a65e] vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
2020-07-11T18:35:17.072769+00:00 app[web.1]: [e15e2d43-88ce-4f5b-ba53-a7fd1984a65e] vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
2020-07-11T18:35:17.072769+00:00 app[web.1]: [e15e2d43-88ce-4f5b-ba53-a7fd1984a65e] vendor/bundle/ruby/2.4.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
2020-07-11T18:35:17.072769+00:00 app[web.1]: [e15e2d43-88ce-4f5b-ba53-a7fd1984a65e] vendor/bundle/ruby/2.4.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
2020-07-11T18:35:17.072770+00:00 app[web.1]: [e15e2d43-88ce-4f5b-ba53-a7fd1984a65e] vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
2020-07-11T18:35:17.072770+00:00 app[web.1]: [e15e2d43-88ce-4f5b-ba53-a7fd1984a65e] vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
2020-07-11T18:35:17.072771+00:00 app[web.1]: [e15e2d43-88ce-4f5b-ba53-a7fd1984a65e] vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/static.rb:127:in `call'
2020-07-11T18:35:17.072771+00:00 app[web.1]: [e15e2d43-88ce-4f5b-ba53-a7fd1984a65e] vendor/bundle/ruby/2.4.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
2020-07-11T18:35:17.072772+00:00 app[web.1]: [e15e2d43-88ce-4f5b-ba53-a7fd1984a65e] vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/ssl.rb:74:in `call'
2020-07-11T18:35:17.072773+00:00 app[web.1]: [e15e2d43-88ce-4f5b-ba53-a7fd1984a65e] vendor/bundle/ruby/2.4.0/gems/railties-5.2.4.3/lib/rails/engine.rb:524:in `call'
2020-07-11T18:35:17.072773+00:00 app[web.1]: [e15e2d43-88ce-4f5b-ba53-a7fd1984a65e] vendor/bundle/ruby/2.4.0/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'
2020-07-11T18:35:17.072773+00:00 app[web.1]: [e15e2d43-88ce-4f5b-ba53-a7fd1984a65e] vendor/bundle/ruby/2.4.0/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'
2020-07-11T18:35:17.072774+00:00 app[web.1]: [e15e2d43-88ce-4f5b-ba53-a7fd1984a65e] vendor/bundle/ruby/2.4.0/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'
2020-07-11T18:35:17.072774+00:00 app[web.1]: [e15e2d43-88ce-4f5b-ba53-a7fd1984a65e] vendor/bundle/ruby/2.4.0/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'
2020-07-11T18:35:17.072775+00:00 app[web.1]: [e15e2d43-88ce-4f5b-ba53-a7fd1984a65e] vendor/bundle/ruby/2.4.0/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread'

```

**Comment by ankane** [comment]
Hey @andrisole92, check out the Contributing Guide for where to get help.

**Comment by andrisole92** [comment]
Hey @ankane, I don't understand why are you closing the issue?

Are you running from something? Or are you ashamed that the gem is not working properly?

I have read the guide and it says:

```
If the above steps don’t help, create an issue. Include:

Detailed steps to reproduce
Complete backtraces for exceptions
```

The above steps didn't help, hence I am posting the issue. Please re-open for good.
