### ISSUE TITLE
Uninitialized constant Ahoy::Visit

### ISSUE THREAD

**Issue by dalezak** [ankane/ahoy#493]
Trying to get `ahoy_matey` wired up, however getting `uninitialized constant Ahoy::Visit` when logging in with `Devise`.

```
uninitialized constant Ahoy::Visit
/.rvm/gems/ruby-2.7.3/bundler/gems/ahoy-cab010aca825/lib/ahoy/database_store.rb:70:in `visit_model'
/.rvm/gems/ruby-2.7.3/bundler/gems/ahoy-cab010aca825/lib/ahoy/database_store.rb:56:in `visit'
/.rvm/gems/ruby-2.7.3/bundler/gems/ahoy-cab010aca825/lib/ahoy/database_store.rb:44:in `authenticate'
/.rvm/gems/ruby-2.7.3/bundler/gems/ahoy-cab010aca825/lib/ahoy/tracker.rb:86:in `authenticate'
/.rvm/gems/ruby-2.7.3/bundler/gems/ahoy-cab010aca825/lib/ahoy/warden.rb:4:in `block in <main>'
/.rvm/gems/ruby-2.7.3/gems/warden-1.2.9/lib/warden/hooks.rb:15:in `block in _run_callbacks'
/.rvm/gems/ruby-2.7.3/gems/warden-1.2.9/lib/warden/hooks.rb:10:in `each'
/.rvm/gems/ruby-2.7.3/gems/warden-1.2.9/lib/warden/hooks.rb:10:in `_run_callbacks'
/.rvm/gems/ruby-2.7.3/gems/warden-1.2.9/lib/warden/manager.rb:52:in `_run_callbacks'
/.rvm/gems/ruby-2.7.3/gems/warden-1.2.9/lib/warden/proxy.rb:191:in `set_user'
/.rvm/gems/ruby-2.7.3/gems/devise-4.8.0/lib/devise/controllers/sign_in_out.rb:53:in `sign_in'
```

Some of my gems from `gem list`:
- rails (6.1.3.2, 6.0.4.1, 6.0.4, 6.0.3.7, 6.0.3.6)
- devise (4.8.0, 4.7.3)
- devise-i18n (1.10.0, 1.9.3)
- devise-jwt (0.9.0, 0.8.1)
- devise_invitable (2.0.5, 2.0.3)
- ahoy_matey (4.0.2)

I tried adding `require "ahoy_matey"` in my `application.rb` but still getting `uninitialized constant`.

I tried versions `4.0.2`, `4.0.1` and `3.3.0` but having the same problem. 

I am using `config.autoload_paths += Dir[Rails.root.join('app', 'models', '**/')]` to load STIs models stored in subfolders, wondering if this is causing the issue here. Anyone else ran into this problem?

**Comment by dalezak** [comment]
Ok, it looks like it was my `config.autoload_paths` that was causing problems. 

Following comment from https://github.com/ankane/ahoy/issues/371#issuecomment-420775560, I updated my models to `class Visit < ApplicationRecord` and `class Event < ApplicationRecord`, then updated `initializers/ahoy.rb`

```
class Ahoy::Store < Ahoy::DatabaseStore
  protected
  def visit_model
    ::Visit
  end
  def event_model
    ::Event
  end
end
```

I am now able to track visits, closing issue.
