### ISSUE TITLE
undefined method `attribute_names' for Ahoy::Event:Class

### ISSUE THREAD

**Issue by jpsilvashy** [ankane/ahoy#506]
I've been upgrading my Rails 6.1 app to Rails 7, when calling `ahoy.track` in my controllers (unchanged in how I was calling this in my Rails 6 app), as an example: `ahoy.track "My first event", language: "Ruby"` 

I receive the following exception:

```
undefined method `attribute_names' for Ahoy::Event:Class
```

Here is the stack trace:

```
[ahoy_matey (4.0.3) lib/ahoy/database_store.rb:78:in `slice_data'](http://localhost:3000/#)
[ahoy_matey (4.0.3) lib/ahoy/database_store.rb:17:in `track_event'](http://localhost:3000/#)
[ahoy_matey (4.0.3) lib/ahoy/tracker.rb:32:in `track'](http://localhost:3000/#)
[app/controllers/blog_posts_controller.rb:26:in `index'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/abstract_controller/base.rb:214:in `process_action'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_controller/metal/rendering.rb:53:in `process_action'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/abstract_controller/callbacks.rb:234:in `block in process_action'](http://localhost:3000/#)
[activesupport (7.0.2.3) lib/active_support/callbacks.rb:118:in `block in run_callbacks'](http://localhost:3000/#)
[actiontext (7.0.2.3) lib/action_text/rendering.rb:20:in `with_renderer'](http://localhost:3000/#)
[actiontext (7.0.2.3) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'](http://localhost:3000/#)
[activesupport (7.0.2.3) lib/active_support/callbacks.rb:127:in `instance_exec'](http://localhost:3000/#)
[activesupport (7.0.2.3) lib/active_support/callbacks.rb:127:in `block in run_callbacks'](http://localhost:3000/#)
[ahoy_matey (4.0.3) lib/ahoy/controller.rb:45:in `set_ahoy_request_store'](http://localhost:3000/#)
[activesupport (7.0.2.3) lib/active_support/callbacks.rb:127:in `block in run_callbacks'](http://localhost:3000/#)
[activesupport (7.0.2.3) lib/active_support/callbacks.rb:138:in `run_callbacks'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/abstract_controller/callbacks.rb:233:in `process_action'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_controller/metal/rescue.rb:22:in `process_action'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'](http://localhost:3000/#)
[activesupport (7.0.2.3) lib/active_support/notifications.rb:206:in `block in instrument'](http://localhost:3000/#)
[activesupport (7.0.2.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'](http://localhost:3000/#)
[sentry-rails (5.2.1) lib/sentry/rails/tracing.rb:54:in `instrument'](http://localhost:3000/#)
[activesupport (7.0.2.3) lib/active_support/notifications.rb:206:in `instrument'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_controller/metal/instrumentation.rb:66:in `process_action'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'](http://localhost:3000/#)
[activerecord (7.0.2.3) lib/active_record/railties/controller_runtime.rb:27:in `process_action'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/abstract_controller/base.rb:151:in `process'](http://localhost:3000/#)
[actionview (7.0.2.3) lib/action_view/rendering.rb:39:in `process'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_controller/metal.rb:188:in `dispatch'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_controller/metal.rb:251:in `dispatch'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_dispatch/routing/route_set.rb:32:in `serve'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_dispatch/journey/router.rb:50:in `block in serve'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_dispatch/journey/router.rb:32:in `each'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_dispatch/journey/router.rb:32:in `serve'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_dispatch/routing/route_set.rb:850:in `call'](http://localhost:3000/#)
[warden (1.2.9) lib/warden/manager.rb:36:in `block in call'](http://localhost:3000/#)
[warden (1.2.9) lib/warden/manager.rb:34:in `catch'](http://localhost:3000/#)
[warden (1.2.9) lib/warden/manager.rb:34:in `call'](http://localhost:3000/#)
[rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'](http://localhost:3000/#)
[rack (2.2.3) lib/rack/etag.rb:27:in `call'](http://localhost:3000/#)
[rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'](http://localhost:3000/#)
[rack (2.2.3) lib/rack/head.rb:12:in `call'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_dispatch/http/permissions_policy.rb:22:in `call'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_dispatch/http/content_security_policy.rb:18:in `call'](http://localhost:3000/#)
[rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'](http://localhost:3000/#)
[rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_dispatch/middleware/cookies.rb:693:in `call'](http://localhost:3000/#)
[activerecord (7.0.2.3) lib/active_record/migration.rb:603:in `call'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'](http://localhost:3000/#)
[activesupport (7.0.2.3) lib/active_support/callbacks.rb:99:in `run_callbacks'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'](http://localhost:3000/#)
[sentry-rails (5.2.1) lib/sentry/rails/rescued_exception_interceptor.rb:12:in `call'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'](http://localhost:3000/#)
[web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'](http://localhost:3000/#)
[web-console (4.2.0) lib/web_console/middleware.rb:28:in `block in call'](http://localhost:3000/#)
[web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'](http://localhost:3000/#)
[web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'](http://localhost:3000/#)
[sentry-ruby-core (5.2.1) lib/sentry/rack/capture_exceptions.rb:26:in `block (2 levels) in call'](http://localhost:3000/#)
[sentry-ruby-core (5.2.1) lib/sentry/hub.rb:199:in `with_session_tracking'](http://localhost:3000/#)
[sentry-ruby-core (5.2.1) lib/sentry-ruby.rb:350:in `with_session_tracking'](http://localhost:3000/#)
[sentry-ruby-core (5.2.1) lib/sentry/rack/capture_exceptions.rb:17:in `block in call'](http://localhost:3000/#)
[sentry-ruby-core (5.2.1) lib/sentry/hub.rb:59:in `with_scope'](http://localhost:3000/#)
[sentry-ruby-core (5.2.1) lib/sentry-ruby.rb:330:in `with_scope'](http://localhost:3000/#)
[sentry-ruby-core (5.2.1) lib/sentry/rack/capture_exceptions.rb:16:in `call'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'](http://localhost:3000/#)
[railties (7.0.2.3) lib/rails/rack/logger.rb:36:in `call_app'](http://localhost:3000/#)
[railties (7.0.2.3) lib/rails/rack/logger.rb:25:in `block in call'](http://localhost:3000/#)
[activesupport (7.0.2.3) lib/active_support/tagged_logging.rb:99:in `block in tagged'](http://localhost:3000/#)
[activesupport (7.0.2.3) lib/active_support/tagged_logging.rb:37:in `tagged'](http://localhost:3000/#)
[activesupport (7.0.2.3) lib/active_support/tagged_logging.rb:99:in `tagged'](http://localhost:3000/#)
[railties (7.0.2.3) lib/rails/rack/logger.rb:25:in `call'](http://localhost:3000/#)
[ahoy_matey (4.0.3) lib/ahoy/engine.rb:22:in `call_with_quiet_ahoy'](http://localhost:3000/#)
[sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'](http://localhost:3000/#)
[request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_dispatch/middleware/request_id.rb:26:in `call'](http://localhost:3000/#)
[rack (2.2.3) lib/rack/method_override.rb:24:in `call'](http://localhost:3000/#)
[rack (2.2.3) lib/rack/runtime.rb:22:in `call'](http://localhost:3000/#)
[activesupport (7.0.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_dispatch/middleware/server_timing.rb:20:in `call'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_dispatch/middleware/static.rb:23:in `call'](http://localhost:3000/#)
[rack (2.2.3) lib/rack/sendfile.rb:110:in `call'](http://localhost:3000/#)
[actionpack (7.0.2.3) lib/action_dispatch/middleware/host_authorization.rb:131:in `call'](http://localhost:3000/#)
[railties (7.0.2.3) lib/rails/engine.rb:530:in `call'](http://localhost:3000/#)
[puma (5.6.4) lib/puma/configuration.rb:252:in `call'](http://localhost:3000/#)
[puma (5.6.4) lib/puma/request.rb:77:in `block in handle_request'](http://localhost:3000/#)
[puma (5.6.4) lib/puma/thread_pool.rb:340:in `with_force_shutdown'](http://localhost:3000/#)
[puma (5.6.4) lib/puma/request.rb:76:in `handle_request'](http://localhost:3000/#)
[puma (5.6.4) lib/puma/server.rb:441:in `process_client'](http://localhost:3000/#)
[puma (5.6.4) lib/puma/thread_pool.rb:147:in `block in spawn_thread'](http://localhost:3000/#)
```

Additionally, the only way I could get the app to boot with Ahoy working as well, was to force the app to initialize with the event model in the initializer defined as such:

``` ruby
class Ahoy::Event < Ahoy::DatabaseStore
  protected
  def event_model
    ::Event
  end
end
```

Curious to if this could be causing my issue? Without this, this is raised during boot:

```
NameError: uninitialized constant Ahoy::Event
```

I would love to contribute to the project, but I'm not sure to start with this one. Thanks again @ankane your projects rock.

**Comment by jpsilvashy** [comment]
Update, oddly enough, I don't think this issue is with Ahoy, but actually with ActiveAdmin. Basically I'm loading in the Ahoy models into Active Admin so you can search and view events and visits and such, something to do with how active admin initialized itself seems to be the issue, I'm going to close this and resolve on that end.

**Comment by ankane** [comment]
Hey @jpsilvashy, it should be `class Ahoy::Store < Ahoy::DatabaseStore` in the code above.
