### ISSUE TITLE
Preload `user` assocation in `database_store`

### ISSUE THREAD

**Issue by philipithomas** [ankane/ahoy#534]
I'm using `strict_loading` in my Rails app. When a user signs in, Ahoy is triggering this error:

```
`Ahoy::Visit` is marked for strict_loading. The Member association named `:user` cannot be lazily loaded.

...
/Users/philip/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/associations/builder/association.rb:104:in `user'
/Users/philip/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ahoy_matey-4.2.1/lib/ahoy/database_store.rb:44:in `authenticate'
/Users/philip/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ahoy_matey-4.2.1/lib/ahoy/tracker.rb:86:in `authenticate'
/Users/philip/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ahoy_matey-4.2.1/lib/ahoy/warden.rb:4:in `block in <main>'
/Users/philip/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/warden-1.2.9/lib/warden/hooks.rb:15:in `block in _run_callbacks'
...
```

I think we can remove an unneeded SQL query by preloading the User association in `database_store.rb`

**Comment by ankane** [comment]
Hi @philipithomas, preloading the user isn't desired most of the time, so you'll want to remove strict loading or override the `authenticate` method of `Ahoy::Store`.

**Comment by philipithomas** [comment]
Thanks!
