### ISSUE TITLE
Visit not created on Rails 4.2.0.beta2

### ISSUE THREAD

**Issue by luopio** [ankane/ahoy#70]
Using the master-branch version of Ahoy. Tried both the LogStore and ActiveRecordStore (with activeuuid from git). 

Events seem to work nicely in both, but I'm not seeing anything in the visits table although a visit ID is present in the event. Here's an example from LogStore (log/events.log):
```
{"id":"fb30adcc-714a-4104-ba18-2ed73e5b1916","name":"Application created","properties":{"property_id":"kellomaki-43-kuopio"},"visit_id":"0ea22a19-c4c5-4db8-9b3c-30ee0ba5e939","visitor_id":"d36bba4e-e309-49f5-9161-4c22e9cdf019","user_id":22,"time":"2015-01-13T11:11:37.528Z"}
```
At the same time there is no log/visits.log. I can see `"Active visit"` in Javascript console. Debugging in a view gives me `current_visit == nil`. Any ideas where I could start debugging this?

**Comment by luopio** [comment]
Calling ahoy.reset() and reloading gives me a `ActionController::InvalidAuthenticityToken` in the background. This is probably the cause. I have `<%= csrf_meta_tags %>` in the application layout. Full stack trace here:

```
ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
  actionpack (4.2.0.beta2) lib/action_controller/metal/request_forgery_protection.rb:180:in `handle_unverified_request'
  actionpack (4.2.0.beta2) lib/action_controller/metal/request_forgery_protection.rb:208:in `handle_unverified_request'
  devise (3.4.0) lib/devise/controllers/helpers.rb:251:in `handle_unverified_request'
  actionpack (4.2.0.beta2) lib/action_controller/metal/request_forgery_protection.rb:203:in `verify_authenticity_token'
  activesupport (4.2.0.beta2) lib/active_support/callbacks.rb:424:in `block in make_lambda'
  activesupport (4.2.0.beta2) lib/active_support/callbacks.rb:160:in `call'
  activesupport (4.2.0.beta2) lib/active_support/callbacks.rb:160:in `block in halting'
  activesupport (4.2.0.beta2) lib/active_support/callbacks.rb:231:in `call'
  activesupport (4.2.0.beta2) lib/active_support/callbacks.rb:231:in `block in halting'
  activesupport (4.2.0.beta2) lib/active_support/callbacks.rb:87:in `call'
  activesupport (4.2.0.beta2) lib/active_support/callbacks.rb:87:in `run_callbacks'
  actionpack (4.2.0.beta2) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.0.beta2) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.0.beta2) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.2.0.beta2) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.0.beta2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.0.beta2) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.0.beta2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.0.beta2) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.0.beta2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.0.beta2) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.0.beta2) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.0.beta2) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.2.0.beta2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.0.beta2) lib/action_controller/metal.rb:236:in `block in action'
  actionpack (4.2.0.beta2) lib/action_dispatch/routing/route_set.rb:72:in `call'
  actionpack (4.2.0.beta2) lib/action_dispatch/routing/route_set.rb:72:in `dispatch'
  actionpack (4.2.0.beta2) lib/action_dispatch/routing/route_set.rb:41:in `serve'
  actionpack (4.2.0.beta2) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.0.beta2) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.0.beta2) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.0.beta2) lib/action_dispatch/routing/route_set.rb:750:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  dragonfly (1.0.3) lib/dragonfly/middleware.rb:14:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.0.beta2) lib/rack/etag.rb:24:in `call'
  rack (1.6.0.beta2) lib/rack/conditionalget.rb:38:in `call'
  rack (1.6.0.beta2) lib/rack/head.rb:13:in `call'
  actionpack (4.2.0.beta2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.0.beta2) lib/action_dispatch/middleware/flash.rb:257:in `call'
  rack (1.6.0.beta2) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.0.beta2) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.0.beta2) lib/action_dispatch/middleware/cookies.rb:558:in `call'
  activerecord (4.2.0.beta2) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.0.beta2) lib/active_record/connection_adapters/abstract/connection_pool.rb:645:in `call'
  activerecord (4.2.0.beta2) lib/active_record/migration.rb:378:in `call'
  actionpack (4.2.0.beta2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.0.beta2) lib/active_support/callbacks.rb:83:in `run_callbacks'
  actionpack (4.2.0.beta2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.0.beta2) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.0.beta2) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  web-console (2.0.0.beta4) lib/action_dispatch/debug_exceptions.rb:18:in `middleware_call'
  web-console (2.0.0.beta4) lib/action_dispatch/debug_exceptions.rb:13:in `call'
  actionpack (4.2.0.beta2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.0.beta2) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.0.beta2) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.0.beta2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.0.beta2) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.0.beta2) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.0.beta2) lib/rails/rack/logger.rb:20:in `call'
  /Users/lauri/.rvm/gems/ruby-2.1.5@lifelife/bundlerahoy (f55bc6a58512) lib/ahoy/engine.rb:20:in `call_with_quiet_ahoy'
  request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
  actionpack (4.2.0.beta2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.0.beta2) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.0.beta2) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.0.beta2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  dragonfly (1.0.3) lib/dragonfly/cookie_monster.rb:9:in `call'
  rack (1.6.0.beta2) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.0.beta2) lib/action_dispatch/middleware/static.rb:103:in `call'
  rack (1.6.0.beta2) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.0.beta2) lib/rails/engine.rb:514:in `call'
  railties (4.2.0.beta2) lib/rails/application.rb:161:in `call'
  rack (1.6.0.beta2) lib/rack/lock.rb:17:in `call'
  rack (1.6.0.beta2) lib/rack/content_length.rb:15:in `call'
  rack (1.6.0.beta2) lib/rack/handler/webrick.rb:89:in `service'
  /Users/lauri/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
  /Users/lauri/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
  /Users/lauri/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

**Comment by luopio** [comment]
I tracked this down to a 422 & 404 returned from /ahoy/visits and finally found that a renegade dev had added `match "*a", to: "application#error_404", via: [:get, :post]` to the end of our routes, which overrode all engine routes. Now I'm seeing visits. Sorry for the noise :)
